[package]
name = "chimper"
version = "0.1.0"
authors = ["Pedro Côrte-Real <pedro@pedrocr.net>"]

[dependencies]
rawloader = "0.31.0"
image = "0.12.2"
rand = "0.3.15"
crossbeam = "0.2.10"
rusttype = "0.2.1"
multicache = "0.1.1"

[dependencies.conrod]
version = "0.51.1"
features = ["glium", "winit"]
git = 'https://github.com/pedrocr/conrod.git'
branch = 'sorted-file-navigator'

[replace]
"glium:0.16.0"  = { git = 'https://github.com/pedrocr/glium.git', branch='fix-from-raw-rgb'}
"winit:0.5.10"  = { git = 'https://github.com/pedrocr/winit.git', branch='maximization' }
"glutin:0.7.4" = { git = 'https://github.com/pedrocr/glutin.git', branch='maximization' }
"image:0.12.2" = { git = 'https://github.com/pedrocr/image.git', branch='ppm-decoder' }

[profile.release]
panic = "unwind"

[profile.dev]
panic = "unwind"
opt-level = 3
