[package]
name = "chimper"
version = "0.1.0"
authors = ["Pedro Côrte-Real <pedro@pedrocr.net>"]

[dependencies]
rawloader = "0.29.0"
conrod = "0.47.4"
piston_window = "0.60.0"
image = "0.10.4"
find_folder = "0.3.0"
rand = "0.3.15"
