[package]
name = "chimper"
version = "0.1.0"
authors = ["Pedro Côrte-Real <pedro@pedrocr.net>"]

[dependencies]
rawloader = "0.30.0"
image = "0.12.2"
rand = "0.3.15"
crossbeam = "0.2.10"
rusttype = "0.2.1"
multicache = "0.1.1"

[dependencies.conrod]
version = "0.50.0"
features = ["glium", "winit"]

[profile.release]
panic = "unwind"

[profile.dev]
panic = "unwind"
opt-level = 3
